
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
  private Connection conn = null;
  private PreparedStatement preparedStatement = null;
  private ResultSet rs = null;
   
  
  /*******************************************************************************************************************************
  Creates a new form Login
 **********************************************************************************************************************************/
    public Login() {
        initComponents();
        conn = DBConnection.connectDB();
        this.setLocationRelativeTo(null);
        loginPanel.setBackground(new Color(0,0,0,100));
       //setLogo();
       
    }
  /*******************************************************************************************************************************
  When this method is called it exits the application
 **********************************************************************************************************************************/   
 
     private void close(){
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
  /*******************************************************************************************************************************
   this method is used to login.
 **********************************************************************************************************************************/
       private void processLogin(){
        try {
            String sql = "SELECT * FROM user WHERE username = ? AND password = ?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtUsername.getText());
            preparedStatement.setString(2, txtPassword.getText());
            rs = preparedStatement.executeQuery();
            if (rs.next()) {
//              JOptionPane.showMessageDialog(null, "Login Successfull!", "Login", JOptionPane.INFORMATION_MESSAGE);
//              Gif g = new Gif();
//             g.setVisible(true);
                new Dashboard().setVisible(true);
                close();
             
            } else {
                JOptionPane.showMessageDialog(null, "Login Unsuccessfull!", "Login", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Something went wrong : " + e.getMessage(), "Login", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        sepPassword = new javax.swing.JSeparator();
        sepUsername = new javax.swing.JSeparator();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Xpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblBluredImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 24), new java.awt.Color(255, 255, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        loginPanel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        loginPanel.setOpaque(false);
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUsername.setToolTipText("Enter username");
        txtUsername.setBorder(null);
        txtUsername.setNextFocusableComponent(txtPassword);
        txtUsername.setOpaque(false);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        loginPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 30));

        sepPassword.setBackground(new java.awt.Color(153, 153, 153));
        sepPassword.setForeground(new java.awt.Color(153, 153, 153));
        loginPanel.add(sepPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 271, 240, 10));

        sepUsername.setBackground(new java.awt.Color(153, 153, 153));
        sepUsername.setForeground(new java.awt.Color(153, 153, 153));
        sepUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sepUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sepUsernameFocusLost(evt);
            }
        });
        sepUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sepUsernameKeyTyped(evt);
            }
        });
        loginPanel.add(sepUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 240, -1));

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setNextFocusableComponent(btnCancel);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        loginPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        loginPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        txtPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setNextFocusableComponent(btnSubmit);
        txtPassword.setOpaque(false);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        loginPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, 30));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Entypo_d83d(0)_32.png"))); // NOI18N
        loginPanel.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lock.png"))); // NOI18N
        loginPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 340, 420));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 230, 130));

        Xpanel.setBackground(new java.awt.Color(29, 35, 59));
        Xpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                XpanelMouseDragged(evt);
            }
        });
        Xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XpanelMousePressed(evt);
            }
        });
        Xpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Iconic_2717(0)_48.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        Xpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, -1));

        getContentPane().add(Xpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));

        lblBluredImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new3.JPG"))); // NOI18N
        lblBluredImage.setOpaque(true);
        getContentPane().add(lblBluredImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Login", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(ans == JOptionPane.YES_OPTION){
            close();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(txtUsername.getText().equals("") || txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "UserName or Password is empty!", "Login", JOptionPane.ERROR_MESSAGE);
        }else{
            processLogin();
        }
        

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        if(txtUsername.getText().equals("") || txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "UserName or Password is empty!", "Login", JOptionPane.ERROR_MESSAGE);
        }else{
            processLogin();
        }
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if(evt.getSource() == txtUsername){
            sepUsername.setForeground(Color.BLACK);
            if(txtUsername.getText().equals("")){
                txtUsername.setText("  Enter Username  ");
                txtUsername.setForeground(Color.LIGHT_GRAY);
            }
            sepUsername.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if(evt.getSource() == txtUsername){
            sepUsername.setForeground(Color.BLACK);
            if(txtUsername.getText().equals("  Enter Username  ")){
                txtUsername.setText("");
                txtUsername.setForeground(Color.WHITE);
            }
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void sepUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sepUsernameKeyTyped
        
    }//GEN-LAST:event_sepUsernameKeyTyped

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
         if(txtUsername.getText().equals("") || txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "UserName or Password is empty!", "Login", JOptionPane.ERROR_MESSAGE);
        }else{
            processLogin();
        }
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void XpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XpanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX,y-mouseY);
    }//GEN-LAST:event_XpanelMouseDragged

    private void XpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XpanelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
                
    }//GEN-LAST:event_XpanelMousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        close();
    }//GEN-LAST:event_jLabel5MousePressed

    private void sepUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sepUsernameFocusGained
       
    }//GEN-LAST:event_sepUsernameFocusGained

    private void sepUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sepUsernameFocusLost
       
    }//GEN-LAST:event_sepUsernameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
         if(evt.getSource() == txtPassword){
            sepPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(evt.getSource() == txtPassword){
            sepPassword.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Xpanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBluredImage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JSeparator sepPassword;
    private javax.swing.JSeparator sepUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
int mouseX;
int mouseY;
}
